POST http://localhost:4242/api/products
Content-Type: application/json

{
      "id": 17,
      "nome": "Harry Potter e o Prisioneiro de Azkaban",
      "descricao": "",
      "categoria": "aventura",
      "preco": "24.90",
      "estoque": "21",
      "nome_arquivo": "harry_potter_e_o_prisioneiro_de_azkaban"
    }



###
GET http://localhost:4242/api/products

### 
GET http://localhost:4242/api/products/649d0f3f4a28fe7764b306d7

###
DELETE http://localhost:4242/api/products

###
DELETE http://localhost:4242/api/products/649d0f3f4a28fe7764b306d7

###
PUT http://localhost:4242/api/products/649d0f3f4a28fe7764b306d7
Content-Type: application/json

{
    "id": 1,
    "nome": "A coragem de ser imperfeito",
    "categoria": "autoajuda",
    "preco": "27.90",
    "estoque": "153",
    "nome_arquivo": "a_coragem_de_ser_imperfeito"
}

###
POST http://localhost:4242/api/clients
Content-Type: application/json

{
    "user": "FelipiYuri",
    "senha": "senhaFacil123#",
    "admin": true
}

###
POST http://localhost:4242/api/clients
Content-Type: application/json

{
    "user": "JONILARE",
    "senha": "senhaDificil123#",
    "admin": false
}

###
GET http://localhost:4242/api/clients

###
GET http://localhost:4242/api/clients/FelipiYuri

###
DELETE http://localhost:4242/api/clients/FelipiYuri

###
PUT http://localhost:4242/api/clients/FelipiYuri
Content-Type: application/json

{
    "user": "JONILARE",
    "senha": "senhaboa123#",
    "admin": false
}