POST http://localhost:4242/api/products
Content-Type: application/json

   {
      "id":50,
      "nome":"Uma Dose Mortal",
      "categoria":"suspense",
      "preco":"23.92",
      "estoque":"27",
      "nome_arquivo":"uma_dose_mortal"
   }
###
GET http://localhost:4242/api/products

### 
GET http://localhost:4242/api/products/649d0f3f4a28fe7764b306d7

###
DELETE http://localhost:4242/api/products/649d0f3f4a28fe7764b306d7

###
PUT http://localhost:4242/api/products/649d0f3f4a28fe7764b306d7
Content-Type: application/json

{
    "id": 1,
    "nome": "A coragem de ser imperfeito",
    "categoria": "autoajuda",
    "preco": "27.90",
    "estoque": "153",
    "nome_arquivo": "a_coragem_de_ser_imperfeito"
}

###
POST http://localhost:4242/api/clients
Content-Type: application/json

{
    "user": "FelipiYuri",
    "senha": "senhaFacil123#",
    "admin": true
}

###
POST http://localhost:4242/api/clients
Content-Type: application/json

{
    "user": "JONILARE",
    "senha": "senhaDificil123#",
    "admin": false
}

###
GET http://localhost:4242/api/clients

###
GET http://localhost:4242/api/clients/FelipiYuri

###
DELETE http://localhost:4242/api/clients/FelipiYuri

###
PUT http://localhost:4242/api/clients/FelipiYuri
Content-Type: application/json

{
    "user": "JONILARE",
    "senha": "senhaboa123#",
    "admin": false
}